### ISSUE TITLE
"Input not an array"

### ISSUE THREAD

**Issue by raufis27** [hardillb/node-red-contrib-color-convert#1]
Could you please provide input example ? No matter what I inject I get "Input not an array" error. 

Thanks.

**Comment by hardillb** [comment]
The README.md and info bar has a pretty good description of all the different input types and without knowing which one you are trying to use I can't give an example.

What would be useful would be if you had given examples of what you have already tried.

**Comment by raufis27** [comment]
Inject string ["0", "100", "50"] > HCL to RGB (output array) > result input not an array

**Comment by hardillb** [comment]
Right,

First, since you're injecting a string, the node is expecting it to be a CSS colour name.

Second, if you change the inject node type to be a JSON object it would probably still fail because you have passed in a array of string.

Change the inject node to use JSON and remove the quote marks.
